export const ADD_DECKS = 'ADD_DECKS'
export const SET_DECKS = 'SET_DECKS'
export const SET_LOADED = 'SET_LOADED'
export const SAVE_NEW_QUESTION = 'SAVE_NEW_QUESTION'
export const ADD_NEW_DECK = 'ADD_NEW_DECK'
